### ISSUE TITLE
客户端部分BUG

### ISSUE THREAD

**Issue by HKTKCLoud** [yangningmou/NetBoardE#1]
<img width="120" alt="image" src="https://github.com/yangningmou/NetBoardE/assets/120702631/b507dd73-7712-4248-9510-dbead9bc61fd">
这个显示账号邮箱的地方建议向下移动一些

![image](https://github.com/yangningmou/NetBoardE/assets/120702631/d6662ade-b5dd-4329-84e7-99dec1a24a89)
如果左边这一栏切换，返回控制面板的时候，红色框标记的位置那些配置就会清空

Windows软件窗口不能拖动，只能固定在一个位置上

**Comment by yangningmou** [comment]
窗口不能拖动的问题
electron规定显示上方菜单栏的才能按住菜单栏拖动
你们不让显示
不显示默认就不能拖动
目前是在前端实时计算拖动距离，然后传递给后端实时改变边界，会有点卡，这种方式因为有的计算机开启比例缩放而导致拖动时自动变大或变小，目前已做优化。
