### ISSUE TITLE
出现显示链接但本地浏览器未挂上代理和切换节点失效

### ISSUE THREAD

**Issue by evanfury** [yangningmou/NetBoardE#3]
打包使用平台：windows npm和 debian pnpm

复现过程：打开登录后直接启动，连接之后出现，无代理情况，重新点击开关可以解决
![1-6.png](https://s2.loli.net/2023/08/28/7OFAPbhiXIcortJ.png)
切换节点失败，要么连上第一个节点不能换要么直连无代理，在多次选择模式后有概率解决问题
![1-4](https://github.com/yangningmou/NetBoardE/assets/53717843/9aca55d3-f548-4c2f-baa9-7622d74deb56)
![1-2](https://github.com/yangningmou/NetBoardE/assets/53717843/cf550496-a203-4c4b-b77f-37cd2414455f)
（节点无问题 服务器均在线）
还有时间出 乱跳
更换内核后依旧
均已经多次复现 辛苦大佬排查修复bug

**Comment by yangningmou** [comment]
时间乱跳已修复。
代理设置应用sysproxy.exe已更换。
切换节点失败问题为规则选择问题，与本应用无关。
